export const mensShoesPage1=[
    {    "id": 63,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l08gsy80/shoe/n/a/n/9-assg1015-9-abros-l-grey-maroon-original-imagc2m9zbzmtybx.jpeg?q=70",
        "brand": "Abros",
        "title": "ASSG1015N Running Shoes For Men",
        "color": "",
        "discountedPrice": 1455,
        "price": 1599,
        "discount": "9% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {   "id": 64,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/o/h/-original-imaggcawtbgvt7wy.jpeg?q=70",
        "brand": "asian",
        "title": "Oxygen-05 Running Shoes For Men",
        "color": "",
        "discountedPrice": 1117,
        "price": 1999,
        "discount": "44% off",
        "size": [{"name": "6"}, {"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {   "id": 65,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/kqidx8w0/shoe/i/4/n/6-brd-406-300-blue-6-birde-blue-original-imag4g8cmfkfzkjg.jpeg?q=70",
        "brand": "BIRDE",
        "title": "Combo Pack of 2 Sports Shoes Running Shoes For Men",
        "color": "",
        "discountedPrice": 499,
        "price": 998,
        "discount": "50% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}]
    },
    {    "id": 66,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/g/i/g/10-rng-2021-blu-orng-44-bruton-blue-orange-original-imagdzcpzhscxwhg-bb.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Sports Running Running Shoes For Men",
        "color": "",
        "discountedPrice": 299,
        "price": 1299,
        "discount": "76% off",
        "size": [{"name": "8"}, {"name": "9"}, {"name": "10"}, {"name": "11"}]
    },
    {   "id": 67,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l4rd0280/shoe/m/d/e/6-rk-494-grey-orange-40-bruton-grey-orange-original-imagfha9ssgydnef.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Sports shoes for men | Latest Stylish Casual for men",
        "color": "",
        "discountedPrice": 249,
        "price": 1299,
        "discount": "80% off",
        "size": [{"name": "6"}, {"name": "7"}, {"name": "8"}, {"name": "9"}]
    },
    {    "id": 68,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/k/k/gm1251-43-good-minar-black-original-imaft34ej4zx2z63-bb.jpeg?q=70",
        "brand": "aadi",
        "title": "Mesh |Lightweight|Comfort|Summer|Trendy|Walking|Outdoor",
        "color": "",
        "discountedPrice": 199,
        "price": 999,
        "discount": "80% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {    "id": 69,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/kuzuoi80/shoe/2/k/x/7-brd-574-brd-575-7-birde-multicolor-original-imag7zx8epryeskm.jpeg?q=70",
        "brand": "BIRDE",
        "title": "Trendy Sport Shoes For Men Pack Of 2 Running Shoes For Men",
        "color": "",
        "discountedPrice": 499,
        "price": 1498,
        "discount": "66% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}]
    },
    {    "id": 70,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/1/8/p/-original-imaghvb7kkpy73vn.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Sports Running Running Shoes For Men",
        "color": "",
        "discountedPrice": 249,
        "price": 1299,
        "discount": "80% off",
        "size": [{"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {   "id": 71,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/q/r/j/-original-imagzjg25cg9wsrj.jpeg?q=70",
        "brand": "CAMPUS",
        "title": "MIKE (N) Running Shoes For Men",
        "color": "",
        "discountedPrice": 949,
        "price": 1699,
        "discount": "44% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {    "id": 72,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/p/l/8-9326-8-world-wear-footwear-yellow-original-imagmengqep9gbwu.jpeg?q=70",
        "brand": "World Wear Footwear",
        "title": "Affordable Range of Stylish Casual Walking Comfortable",
        "color": "",
        "discountedPrice": 249,
        "price": 998,
        "discount": "75% off",
        "size": [{"name": "6"}, {"name": "7"}, {"name": "8"}, {"name": "9"}]
    },
    {   "id": 73,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/1/s/j/8-east-8-jqr-l-gry-original-imagjueg2zfewfpg.jpeg?q=70",
        "brand": "JQR",
        "title": "EAST COOLSENSE lightweight, trendy stylish, stretchable",
        "color": "",
        "discountedPrice": 811,
        "price": 1249,
        "discount": "35% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {    "id": 74,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/s/j/9/-original-imaghrfzmsz9e6kh.jpeg?q=70",
        "brand": "NIVIA",
        "title": "Super Court 2.0 Badminton Shoes For Men",
        "color": "",
        "discountedPrice": 1047,
        "price": 1999,
        "discount": "47% off",
        "size": [{"name": "6"}, {"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {   "id": 75,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l4oi4cw0/shoe/g/u/e/6-blk-482-40-bruton-black-red-original-imagfgp97vzhyne2.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Trendy Sports Running Running Shoes For Men",
        "color": "",
        "discountedPrice": 249,
        "price": 1299,
        "discount": "80% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}]
    },
    {    "id": 76,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/l0igvww0/shoe/j/x/z/7-brd-678-7-birde-blue-original-imagca7bcj6p99gw.jpeg?q=70",
        "brand": "BIRDE",
        "title": "Stylish Comfortable Lightweight, Breathable Black Running",
        "color": "",
        "discountedPrice": 299,
        "price": 999,
        "discount": "70% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {   "id": 77,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/i/k/r/-original-imaghugwugwyczwc.jpeg?q=70",
        "brand": "asian",
        "title": "Future-01 running shoes For Men",
        "color": "",
        "discountedPrice": 514,
        "price": 999,
        "discount": "48% off",
        "size": [{"name": "6"}, {"name": "7"}, {"name": "8"}, {"name": "9"}]
    },
    {   "id": 78,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/r/j/c/-original-imaghvb8a8hjrfmr.jpeg?q=70",
        "brand": "CAMPUS",
        "title": "STREET-RUN Running Shoes For Men",
        "color": "",
        "discountedPrice": 1329,
        "price": 1799,
        "discount": "26% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {    "id": 79,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/9/h/e/10-bd-1191bl-10-nivia-blue-original-imagndzhu9sgpyzf.jpeg?q=70",
        "brand": "NIVIA",
        "title": "Badminton Shoes For Men",
        "color": "",
        "discountedPrice": 896,
        "price": 1120,
        "discount": "20% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}, {"name": "10"}]
    },
    {    "id": 80,
        "imageUrl": "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/h/e/7-rng-2cmb-2031-551-41-bruton-blue-white-original-imaggameyhax2hwu.jpeg?q=70",
        "brand": "BRUTON",
        "title": "Combo Pack of 2 | sports shoes for men |walking, gym, trend",
        "color": "",
        "discountedPrice": 499,
        "price": 2499,
        "discount": "80% off",
        "size": [{"name": "7"}, {"name": "8"}, {"name": "9"}]
    },
]
