export const womensTopData = [
  {
    id: 1,
    title: "Floral Print Blouse",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    image: "/src/assets/floral-blouse.jpg",
    brand: "Zara",
    category: "Women",
    subcategory: "Top",
    color: "Multicolor",
    size: ["S", "M", "L", "XL"],
    rating: 4.2,
    reviews: 128,
  },
  {
    id: 2,
    title: "Classic White Shirt",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    image: "/src/assets/floral-blouse.jpg",
    brand: "H&M",
    category: "Women",
    subcategory: "Top",
    color: "White",
    size: ["S", "M", "L", "XL"],
    rating: 4.5,
    reviews: 256,
  },
  {
    id: 3,
    title: "Striped Crop Top",
    price: 699,
    originalPrice: 999,
    discount: 30,
    image: "/src/assets/floral-blouse.jpg",
    brand: "Forever 21",
    category: "Women",
    subcategory: "Top",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    rating: 4.0,
    reviews: 89,
  },
  {
    id: 4,
    title: "Black Lace Top",
    price: 1599,
    originalPrice: 2299,
    discount: 30,
    image: "/src/assets/floral-blouse.jpg",
    brand: "Mango",
    category: "Women",
    subcategory: "Top",
    color: "Black",
    size: ["S", "M", "L"],
    rating: 4.3,
    reviews: 167,
  },
  {
    id: 5,
    title: "Denim Jacket",
    price: 2499,
    originalPrice: 3499,
    discount: 29,
    image: "/src/assets/floral-blouse.jpg",
    brand: "Levi's",
    category: "Women",
    subcategory: "Top",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviews: 312,
  },
  {
    id: 6,
    title: "Silk Camisole",
    price: 1899,
    originalPrice: 2699,
    discount: 30,
    image: "/src/assets/floral-blouse.jpg",
    brand: "Gucci",
    category: "Women",
    subcategory: "Top",
    color: "Red",
    size: ["XS", "S", "M", "L"],
    rating: 4.4,
    reviews: 98,
  },
  {
    id: 7,
    title: "Graphic Tee",
    price: 599,
    originalPrice: 899,
    discount: 33,
    image: "/src/assets/floral-blouse.jpg",
    brand: "Nike",
    category: "Women",
    subcategory: "Top",
    color: "Gray",
    size: ["S", "M", "L", "XL"],
    rating: 4.1,
    reviews: 203,
  },
  {
    id: 8,
    title: "Off-Shoulder Top",
    price: 1099,
    originalPrice: 1599,
    discount: 31,
    image: "/src/assets/floral-blouse.jpg",
    brand: "Zara",
    category: "Women",
    subcategory: "Top",
    color: "Pink",
    size: ["S", "M", "L"],
    rating: 4.2,
    reviews: 145,
  },
];
